# Generated by Django 3.2.7 on 2021-09-14 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('correctAnswerID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=100)),
                ('checkAnswerBool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mcq', 'MCQ'), ('one_word', 'one_word')], max_length=30)),
                ('marks', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DurationField(blank=True)),
                ('quizDescription', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('history', 'History'), ('geography', 'Geography'), ('science', 'science'), ('maths', 'Maths')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('answerId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('textAnswer', models.CharField(blank=True, max_length=100)),
                ('remainingTime', models.DurationField(blank=True)),
                ('currentScore', models.IntegerField(default=0)),
                ('examCompleted', models.BooleanField(default=False)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('correctAnswerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.correctanswer')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quizId',
            field=models.ManyToManyField(to='QuizApp.Quiz'),
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='questionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.question'),
        ),
    ]
