# Generated by Django 3.2.7 on 2021-09-22 06:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quizDescription', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('alloted_time', models.IntegerField(default=5)),
                ('category', models.CharField(choices=[('history', 'History'), ('geography', 'Geography'), ('science', 'science'), ('maths', 'Maths'), ('entertainment', 'Entertainment'), ('vehicle', 'vehicle')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mcq', 'MCQ'), ('one_word', 'one_word')], max_length=30)),
                ('marks', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=1000)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QuizApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('options', models.CharField(max_length=100)),
                ('checkAnswerBool', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='QuizApp.question')),
            ],
        ),
    ]
