# Generated by Django 3.2.7 on 2021-09-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quizId',
        ),
        migrations.AddField(
            model_name='question',
            name='quizId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='QuizApp.quiz'),
            preserve_default=False,
        ),
    ]
