# Generated by Django 3.2.7 on 2021-09-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_progress_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='QuizApp.question'),
        ),
    ]
