# Generated by Django 3.2.7 on 2021-09-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_alter_progress_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='checkAnswerBool',
            new_name='check_answer_bool',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quizDescription',
            new_name='quiz_description',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='textAnswer',
            new_name='user_answer',
        ),
    ]
