# Generated by Django 3.2.7 on 2021-09-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_alter_quiz_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('history', 'History'), ('geography', 'Geography'), ('science', 'science'), ('maths', 'Maths')], max_length=100, unique=True),
        ),
    ]
