# Generated by Django 3.2.7 on 2021-09-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_alter_quiz_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='correctAnswerID',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='textAnswer',
            field=models.CharField(max_length=100),
        ),
    ]
