# Generated by Django 3.2.7 on 2021-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0006_auto_20210915_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='textAnswer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
