# Generated by Django 3.2.7 on 2021-09-15 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0008_alter_useranswer_textanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='remainingTime',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
