# Generated by Django 3.2.7 on 2021-09-18 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0009_alter_useranswer_remainingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='remainingTime',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=300)),
        ),
    ]
