# Generated by Django 3.2.7 on 2021-09-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0010_alter_useranswer_remainingtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='examCompleted',
        ),
    ]
