# Generated by Django 3.2.7 on 2021-09-18 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuizApp', '0011_remove_useranswer_examcompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='remainingTime',
        ),
        migrations.AddField(
            model_name='quiz',
            name='alloted_time',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minutes', models.IntegerField(default=1)),
                ('seconds', models.IntegerField(default=60)),
                ('subject', models.CharField(max_length=20)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.question')),
            ],
        ),
    ]
