# Generated by Django 3.2.7 on 2021-09-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0012_auto_20210918_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('history', 'History'), ('geography', 'Geography'), ('science', 'science'), ('maths', 'Maths'), ('entertainment', 'Entertainment')], max_length=100, unique=True),
        ),
    ]
