# Generated by Django 3.2.7 on 2021-09-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0013_alter_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('history', 'History'), ('geography', 'Geography'), ('science', 'science'), ('maths', 'Maths'), ('entertainment', 'Entertainment'), ('vehicle', 'vehicle')], max_length=100, unique=True),
        ),
    ]
