# Generated by Django 3.2.7 on 2021-09-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0014_alter_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='textAnswer',
            field=models.CharField(blank=True, max_length=100, verbose_name=''),
        ),
    ]
