# Generated by Django 3.2.7 on 2021-09-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0015_alter_useranswer_textanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctanswer',
            old_name='checkAnswerBool',
            new_name='check_answer_bool',
        ),
        migrations.RenameField(
            model_name='correctanswer',
            old_name='correctAnswerID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='correctanswer',
            old_name='questionID',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='questionID',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='UserId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quizId',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quizId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quizDescription',
            new_name='quiz_description',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='currentScore',
            new_name='current_score',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='answerId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='questionID',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='UserId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='textAnswer',
            new_name='user_answer',
        ),
    ]
